apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - name: mysql-client
    image: percona/percona-server:8.0.25
    command:
    - sleep
    - infinity
    volumeMounts:
      - mountPath: /tmp/imdb
        name: hostpath-mount
  volumes:
    - name: hostpath-mount
      hostPath:
        path: /tmp/repos/imdb
